---
title: "PRC_2"
author: "Iker Fernández Cabanillas"
date: "2026-02-25"
output: pdf_document
---

```{r}
library(haven)
data1 <- read_sas("C:/Users/ikerf/Downloads/TERCERO/SegundoCuatri/M_Avançada/PRCS/PRC2/uab_demo2.sas7bdat", 
    NULL)

data2 <- read_sas("C:/Users/ikerf/Downloads/TERCERO/SegundoCuatri/M_Avançada/PRCS/PRC2/uab_atc_drugs2.sas7bdat", 
    NULL)

data3 <- read_sas("C:/Users/ikerf/Downloads/TERCERO/SegundoCuatri/M_Avançada/PRCS/PRC2/uab_drugs2.sas7bdat", 
    NULL)
```

```{r}
data_2=merge(data1,data2,by.x="PatNo", by.y = "PatNo")
data_f=merge(data_2,data3,by.x="PatNo", by.y = "PatNo")
write.csv(data_f,"dataf.csv")
```


Anàlisi descriptiva entre grups

```{r,results=F}
library(dplyr)
library(tableone)


variables_farmacs <- c("insulinaDias", "ActPrevantiulceros_IBP", "ActualCortis_sistemics", "N06AA_SN", 
                       "ADepreISRSCur", "CortInh", "PrevioCortis_sistemics", "N06AB_SN", "N06A_SN", 
                       "ADepreNoISRSDias", "R03BA_SN", "ADepreISRS6m", "PrevioBisfosfonats", 
                       "ActPrevCortis_sistemics", "ActualADO_glitazona", "ADepreISRS", "ADepreISRSDias", 
                       "N_SN", "insulina", "ADepreNoISRSCur", "ActualCortis_inhalats", "H01_SN", 
                       "N06AX_SN", "ActPrevinsulina", "Actualantiulceros_IBP", "ActPrevCortis_inhalats", 
                       "BisfDias", "ADO_no_glitazonaDias", "ActPrevBisfosfonats", "CortSistIniBf3m", 
                       "CortInhIniBf3m", "Previoantidepressiu_no_ISRS", "ActPrevantidepressiu_ISRS", 
                       "CortSistDias", "H02_SN", "H_Dias", "PrevioCortis_inhalats", "CortSistExpLt3m", 
                       "CortSistExpCat", "H_SN", "Actualosteoporosi_no_bisfosfonat", "ADepreNoISRS6m", 
                       "Bisf", "PrevioADO_glitazona", "CortInhExpCat", "Actualinsulina", "CortInhExpLt3m", 
                       "ActPrevADO_glitazona", "H02_Dias", "CortSist", "ADepreNoISRS", "Previoinsulina", 
                       "R03BA_Dias", "Actualantidepressiu_no_ISRS", "ADO_no_glitazona", "BisfExpCat", 
                       "Previoantiulceros_IBP", "Actualantidepressiu_ISRS", "ADO_glitazonaDias", 
                       "Previoantidepressiu_ISRS", "N06_SN", "ActualBisfosfonats")


variables_cat=variables_farmacs[!grepl("Dias", variables_farmacs)]

taula_an <- CreateTableOne(
  vars = variables_farmacs , 
  strata = "Grup.x", 
  data = data_f,
  factorVars = variables_cat
)

tbl=print(taula_an)
class(tbl)
```

```{r}
library(knitr)
kable(tbl,caption = "Comparació de Medicaments i teràpies")
View(data_f)
```

